### PR TITLE
Add the kinds of metrics we'll track to readme.md

### PR DESCRIPTION
**Pull request by carodew**
This PR adds project metrics to the readme.md and fulfills issue #7 

It looks like this PR caught a couple commits from @thisisdano but also only the readme.md file changed so I don't think anything is messed up. 🤞

### CODE REVIEW

**Comment by willcahoe** [comment]
## User groups and metrics
1. We believe that creative civil servants across government have ideas for how to solve government problems and need funding and guidance to pursue those ideas. We believe that by providing information about how to pitch ideas to 10x:
    - More people will submit pitches for Phase 1 funding overall.
    - We’ll receive more ideas for Phase 1 funding from civil servants outside of GSA as subject-matter experts (through a TTS sponsor).
    - We’ll receive pitches for Phase 1 funding that represent a greater number of agencies as subject-matter experts.
2. GSA leadership and oversight bodies
    - [TBD]
3. We believe that there are civil servants who manage technology or innovation funds who are unhappy about how they are investing those dollars. We believe that if we provide tools and resources for managing those funds following the 10x model:
    - We’ll receive inquiries from civil servants about how to set up a 10x program.
    - Civil servants will hire 10x to consult with them on setting up or running their own program.

My suggestions: I removed the "type of agencies" bullet, because I'm not sure if that's something we are measuring. To me, simply receiving pitches from many different agencies is enough. Do you want me to add some target numbers to the metrics after I comb through some of the docs to see where our baseline numbers fall?

**Comment by carodew** [comment]
@willcahoe I had doubts about the types of agencies as well, since it would require us to decide what types we want to look at (big or small? Grant making agencies? Independent agencies? ??) which doesn't feel like something we want to prioritize right now. 

We can add target metrics but I'm also ok with just deciding what direction we want the metrics to go in. (aka, we want number of different agencies to go up, if it goes down or stays the same we'll be super sad). It's kind of up to what 10x wants. Either way let's do that in a separate pull request.

**Comment by carodew** [comment]
One moment and I'll update the PR to remove types of agencies

**Comment by carodew** [comment]
@willcahoe made the change – if you're good with it feel free to hit the big green button!

**Pull request merged**
