### PR TITLE
publish multilingual glossary tool project card/page

### PR DESCRIPTION
**Pull request by sknep**
https://demo.10x.gsa.gov/projects/multilingual-glossary-tool/

### CODE REVIEW

**Comment by sknep** [comment]
The phase timeline always starts with "Phase 1" on every project page, even if it's not in Phase 1. I did put "Phase 3" below the timeline to make it clearer, but it's part of the current template.

**Comment by maomeara63** [comment]
@sknep The Phase info is odd:

image

**Comment by maomeara63** [comment]
> @sknep The Phase info is odd:
> 
> image

Actually, I think my thinking was wrong. I think the phase info was right before. (We need to remove the Phase 3 text.)

**Comment by jonadecker** [comment]
I might also consider going for even more brevity, e.g., What if government information was translated using high quality, consistent language?

I also feel like the title on BEARS is aggressively wordy.

**Comment by maomeara63** [comment]
@sknep Renata is okay with Jona's title suggestion. Can we make it so?

**Comment by maomeara63** [comment]
For visibility, Renata requested "What if government information was translated using consistent terms to improve the quality of communications?" as the most accurate but short title. It has been changed to this.

**Review by maomeara63 — APPROVED** [review]

**Pull request merged**
